name: UI-Kit master
on:
  push:
    branches: [ master ]
  release:
    types: [ created ]

jobs:
  master:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-ui-kit-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-ui-kit-

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Check license
        run: ./gradlew license

      - name: Build and test library
        run: ./gradlew build --info

      - name: Publish to Maven Central
        run: ./gradlew publishToSonatype closeAndReleaseSonatypeStagingRepository
        env:
          ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.SONATYPE_USERNAME }}
          ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.SONATYPE_PASSWORD }}

      - name: Create showcase distribution
        run: ./gradlew browserDistribution

      - name: Deploy showcase to Github Pages
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: docs
          folder: ui-kit-showcase/build/distributions
          single-commit: true
