name: UI-Kit master
on:
  push:
    branches: [ master ]

jobs:
  master:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-ktorbase-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-ktorbase-

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Check license
        run: ./gradlew license

      - name: Build and test library
        run: ./gradlew test build --info

        # The USERNAME and TOKEN need to correspond to the credentials environment variables used in
        # the publishing section of your build.gradle
      - name: Publish to GitHub Packages
        run: |
          echo "Github username: ${GITHUB_ACTOR}"
          ./gradlew publish
        env:
          GITHUB_TOKEN: ${{ secrets.GH_API_TOKEN }}
